databases:
  - name: Tesla car booking
    databaseName: tesla_car_booking
    user: tesla_car_booking_user

services:
  - type: web
    name: Tesla car booking
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tesla_car_booking
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false